### ISSUE TITLE
Авторизация на сайте через соц. сети

### ISSUE THREAD

**Issue by Leningradez** [Piter-United/puportal#5]
Как Посетитель,
хочу иметь возможность авторизоваться через социальные сети
* Github
* G+
* Fb
* Vk
* LinkedIn
чтобы быть в курсе о событиях сообществ, участником которых я являюсь и получать краткую еженедельную рассылку по всем предстоящим митапа (настраиваться будет).

**Comment by zinenko** [comment]
@Leningradez, @tigusigalpa готово в #10
